### ISSUE TITLE
iOS Simulator Linker Error libtorch

### ISSUE THREAD

**Issue by noob8boi** [abdelaziz-mahdy/pytorch_lite#74]
I get this error when I try to run my app on simulator for taking screenshots.. Preparing it for app store launch. 

```
Error (Xcode): Building for 'iOS-simulator', but linking in object file (/Users/xyz/Desktop/abc/abc_app/ios/Pods/LibTorch/install/lib/libtorch.a[arm64][2](empty.cpp.o)) built for 'iOS'

Error (Xcode): Linker command failed with exit code 1 (use -v to see invocation)
```

Any suggestions?

**Comment by abdelaziz-mahdy** [comment]
Can you provide flutter doctor output

**Comment by noob8boi** [comment]
> Can you provide flutter doctor output

![image](https://github.com/abdelaziz-mahdy/pytorch_lite/assets/91360152/b8e31835-6a3d-4111-acef-4e2599a0c4c1)
btw it works well on physical devices.

**Comment by abdelaziz-mahdy** [comment]
it works for me on simulator, i have same flutter version as you, so i dont know where is the problem :_(

**Comment by noob8boi** [comment]
> it works for me on simulator, i have same flutter version as you, so i dont know where is the problem :_( 

After I excluded arm64 architecture from build settings in xcode.. it started to work. Welp resolved now :)

**Comment by abdelaziz-mahdy** [comment]
Glad to know
