### ISSUE TITLE
Error pytorch classification

### ISSUE THREAD

**Issue by HIDR00** [abdelaziz-mahdy/pytorch_lite#77]
import torch
from torch.utils.mobile_optimizer import optimize_for_mobile

model = torch.load('best.pt', map_location='cpu')
model.eval()

example = torch.rand(1, 3, 224, 224)

traced_script_module = torch.jit.trace(model, example)

optimized_traced_model = optimize_for_mobile(traced_script_module)

optimized_traced_model._save_for_lite_interpreter('model.pt')
i put my model best.pt but it show error:
AttributeError: 'dict' object has no attribute 'eval'

**Comment by abdelaziz-mahdy** [comment]
Please check your best.pt looks like it's not working correctly, or try another one

**Comment by HIDR00** [comment]
![image](https://github.com/abdelaziz-mahdy/pytorch_lite/assets/115889838/21e8bbb3-ad5e-42f9-9959-34633196726d)
i use yolov8 to train custom and get best.pt from run/detect/weights

**Comment by abdelaziz-mahdy** [comment]
Maybe the weights didn't get saved correctly, also yolo conversion method is different please recheck the redme

**Comment by HIDR00** [comment]
![image](https://github.com/abdelaziz-mahdy/pytorch_lite/assets/115889838/fef1f50b-5898-4b84-a53b-a0feef412cfa)
"My model is still working fine. Have you tried using YOLOv8 for this Flutter package yet?"

**Comment by abdelaziz-mahdy** [comment]
Yes yolo V8 is supported 

I didn't test the classification yolo but it should work 

Please export the model using yolo export

**Comment by abdelaziz-mahdy** [comment]
Command 
`!yolo mode=export model="your model" format=torchscript optimize`
