### ISSUE TITLE
Is the rotation argument in getCameraImagePrediction a valid value?

### ISSUE THREAD

**Issue by silvershort** [abdelaziz-mahdy/pytorch_lite#80]
Looking at the API, getCameraImagePrediction calls the getCameraImagePredictionList method. The rotation parameter value is not used inside the getCameraImagePredictionList method.

Currently, I am trying to implement real-time object detection through cameraController.startImageStream. I can receive the CameraImage class as the Stream callback value, but I don't know the exact reason, but there was a problem that the image in IOS was rotated 90 degrees. To solve this, I tried adjusting the rotation value of getCameraImagePrediction, but I confirmed that there was no change even if I adjusted the value in various ways.

```
/// Retrieves a list of [ResultObjectDetection] by predicting the objects in the given [cameraImage].
  /// The [rotation] parameter specifies the rotation of the camera image.
  /// The optional parameters [minimumScore], [iOUThreshold], [boxesLimit], [cameraPreProcessingMethod], and [preProcessingMethod]
  /// allow customization of the prediction process.
  Future<List<ResultObjectDetection>> getCameraImagePredictionList(
      CameraImage cameraImage, int rotation,
      {double minimumScore = 0.5,
      double iOUThreshold = 0.5,
      int boxesLimit = 10,
      CameraPreProcessingMethod cameraPreProcessingMethod =
          CameraPreProcessingMethod.imageLib,
      PreProcessingMethod preProcessingMethod =
          PreProcessingMethod.imageLib}) async {
    if (cameraPreProcessingMethod == CameraPreProcessingMethod.imageLib) {
      // Convert the camera image to bytes using ImageUtilsIsolate
      Uint8List? bytes =
          await ImageUtilsIsolate.convertCameraImageToBytes(cameraImage);
      if (bytes == null) {
        throw Exception("Unable to process image bytes");
      }
      // Get the image prediction list using the converted bytes
      return await getImagePredictionList(bytes,
          minimumScore: minimumScore,
          iOUThreshold: iOUThreshold,
          boxesLimit: boxesLimit,
          preProcessingMethod: preProcessingMethod);
    }
    // Get the image prediction list directly from the camera image planes
    return await getImagePredictionFromBytesList(
        cameraImage.planes.map((e) => e.bytes).toList(),
        cameraImage.width,
        cameraImage.height,
        minimumScore: minimumScore,
        iOUThreshold: iOUThreshold,
        boxesLimit: boxesLimit);
  }
```

------
Flutter - Channel stable, 3.24.0
pytorch_lite: ^4.2.6

**Comment by abdelaziz-mahdy** [comment]
I can't test iOS code due to not having an iPhone, so check these it may help you figure out the problem 
https://github.com/abdelaziz-mahdy/pytorch_lite/issues/41#issuecomment-2213742502

If you were able to submit a pr I would appreciate it

**Comment by silvershort** [comment]
> I can't test iOS code due to not having an iPhone, so check these it may help you figure out the problem [#41 (comment)](https://github.com/abdelaziz-mahdy/pytorch_lite/issues/41#issuecomment-2213742502)
> 
> If you were able to submit a pr I would appreciate it

The core of this issue is that the 'rotation' parameter is not used. The reason why the Stream image appears rotated on iOS is not a problem with this package. (It's probably a problem with the Camera package or my project environment.)

I forked the package and made a code that uses the rotation parameter and it works fine.

However, I'm not sure if the rotation argument is supposed to take an int value between 0 and 360, or a constant value that matches a specific angle value, e.g. 90, 180, 270.

I'm cautious about sending a PR because this part should be designed according to the intention of the package creator. Can you check what I committed and update the package?

https://github.com/silvershort/pytorch_lite/commit/06e6548963e17ad54f29fecf1885a59da39100ee

**Comment by abdelaziz-mahdy** [comment]
Convert camera image should do that operation if I remember correctly, and if you would like to open a pr that's very good, I can review it and merge if all is okay 

I am trying to minimize encode and decode calls since they are slow

**Comment by abdelaziz-mahdy** [comment]
fixed by https://github.com/abdelaziz-mahdy/pytorch_lite/pull/81 and released
