### ISSUE TITLE
custom PyTorch model

### ISSUE THREAD

**Issue by muhammedakyuzlu** [abdelaziz-mahdy/pytorch_lite#84]
I have a custom PyTorch model, similar to a UNet, currently saved in .pt format. What steps should I take to use this model with this package? Additionally, are there general guidelines for integrating custom PyTorch architectures, aside from models like YOLO?

**Comment by abdelaziz-mahdy** [comment]
There should be not, I am using the official pytorch sdks for each platform 


But you will have to make sure the same input as in same image parameters and normalizations and you will have to convert the model output to rects on your own
