### ISSUE TITLE
YOLO v11 Support

### ISSUE THREAD

**Issue by roscoekerby** [abdelaziz-mahdy/pytorch_lite#87]
Hi pytorch_lite contributors,

First off, thank you for all the hard work you've put into this fantastic project!

I’m reaching out to kindly request support for the latest YOLOv11 model from Ultralytics. With its improved efficiency, accuracy, and flexibility, YOLOv11 would be a great addition to pytorch_lite's supported models. The official documentation for YOLOv11 can be found here: [Ultralytics YOLOv11 Documentation](https://docs.ultralytics.com/models/yolo11/), and the GitHub repository is available here: [Ultralytics GitHub Repository](https://github.com/ultralytics/ultralytics).

While I’d love to contribute to this myself, I feel that I may not yet have the required proficiency to handle this update independently. If there’s a way for me to assist or collaborate with others in the community to make this happen, I’d be more than happy to contribute in any way I can.

Looking forward to your thoughts and guidance!

Best regards,
ROSCODE 
(Roscoe Kerby)

**Comment by abdelaziz-mahdy** [comment]
Thank you for the issue, and will look into it when I get some free time since I am quite busy these days

**Comment by abdelaziz-mahdy** [comment]
hi, i just tested out yolov11 and using the model selection as yolov8 works correctly 

```
      _objectModelYoloV11 = await PytorchLite.loadObjectDetectionModel(
        pathObjectDetectionModelYolov11,
        80,
        640,
        640,
        labelPath: "assets/labels/labels_objectDetection_Coco.txt",
        objectDetectionModelType: ObjectDetectionModelType.yolov8
      );
```

https://github.com/abdelaziz-mahdy/pytorch_lite/pull/88 this a pr adding the example, i tested on android but it should work correctly for ios too
