### ISSUE TITLE
I suggest deleting the yolo model files from example.

### ISSUE THREAD

**Issue by sun-jiao** [abdelaziz-mahdy/pytorch_lite#89]
Mainly for the following two reasons:

1. Ultralytics thinks that their [AGPL license applies to the weights](https://github.com/ultralytics/ultralytics/issues/2129). Because of that, this project should also be licensed under AGPL. Although I think their opinion is completely bullshit, it would not be a good experience if they come to you or users of your library. 
2. Including weight data bloats the size of the library. It takes 95.4 MB in my `pub-cache`, 90 MB of which is taken by the weights.

If you insist on putting the weights files inside the example, I think it would be a good idea to ignore them when publishing new releases on pub.dev.

[WongKinYiu](https://github.com/WongKinYiu) has re-implemented [YOLO](https://github.com/WongKinYiu/YOLO) and licensed it under MIT.

**Comment by abdelaziz-mahdy** [comment]
Thank you for bringing up this issue! The main reason the examples include models is to allow users to test the example app without needing to add their own models. Removing them might make testing more inconvenient. However, I’m not entirely sure of the best way to handle this. I’m open to suggestions if you have any ideas!

**Comment by abdelaziz-mahdy** [comment]
i think your idea is valid, i will ignore the models from pub since its not used anyway, and if people want to build the example they build using github

**Comment by abdelaziz-mahdy** [comment]
pytorch_lite: ^4.3.1 published, now package size on pub is 90 kb :) nice

**Comment by sun-jiao** [comment]
Great!
